# Generated by Django 4.0.3 on 2022-04-08 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime.now),
        ),
    ]
