# Generated by Django 4.0.3 on 2022-03-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionsAttended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('year', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='title',
        ),
    ]
